version: '3.7'
services:
  mysql:
    image: mysql:8.0
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: events_db

    volumes:
    - dbdata:/var/lib/mysql


volumes:
  dbdata:   
