version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  networks:
    app-network:
      driver: bridge

  volumes:
    db-data:
      driver: local


  
