version: '3.8'

services:

  app:
    image: events:latest
    build:
      context: .
      dockerfile: event.dockerfile
    command: python3 app.py
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"
    env_file:
      - event.env


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: events
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  
